AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.6.0

Style/ClassAndModuleChildren:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  MinNameLength: 1
Style/CommandLiteral:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Lint/RescueException:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 300
Metrics/AbcSize:
  Max: 130
Metrics/BlockLength:
  Max: 250
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
Metrics/LineLength:
  Max: 120
Metrics/ParameterLists:
  Max: 10
Layout/EmptyLineAfterGuardClause:
  Enabled: false
